(()=>{
  const X=window.DIExperience;if(!X)return;
  const P='di-guerras-';
  const defaults={embers:true,sparks:true,ash:true,'hot-dust':true,turbulence:true,'front-particles':true,'clan-texture':true,'metal-reflection':true,'map-texture':true,'menu-motion':true,'ember-density':92,'motion-intensity':52,'effect-opacity':86};
  const getBool=k=>X.bool(P+k,defaults[k]),getNum=(k,min=0,max=100)=>X.num(P+k,defaults[k],min,max);
  const particleSources={ember:[],spark:[],ash:[]};
  const particleSprites={};
  for(const [key,value] of Object.entries(particleSources)){
    const paths=Array.isArray(value)?value:[value];particleSprites[key]=paths.map(src=>{const image=new Image();image.decoding='async';image.src=src;return image});
  }
  const readySprite=(type,index=0)=>{const list=particleSprites[type]||[];const image=list[index%Math.max(1,list.length)];return image?.complete&&image.naturalWidth?image:null};
  Object.entries(defaults).forEach(([k,v])=>{if(X.storage.get(P+k)===null)X.storage.set(P+k,typeof v==='boolean'?(v?'1':'0'):v)});
  // maxParticles reduz a densidade em weakDevice; partículas frontais continuam disponíveis no mobile.

  const back=document.createElement('canvas'),front=document.createElement('canvas'),clouds=document.createElement('div');
  back.id='warParticleBack';front.id='warParticleFront';clouds.className='war-night-clouds';back.setAttribute('aria-hidden','true');front.setAttribute('aria-hidden','true');clouds.setAttribute('aria-hidden','true');
  document.body.prepend(front);document.body.prepend(back);document.body.prepend(clouds);
  const contexts=[{canvas:back,ctx:back.getContext('2d'),front:false,particles:[]},{canvas:front,ctx:front.getContext('2d'),front:true,particles:[]}];
  let running=true,last=performance.now(),wind=0,targetWind=0,nextGust=performance.now()+3500,raf=0;
  function resize(){const dpr=Math.min(devicePixelRatio||1,1.6);for(const layer of contexts){layer.canvas.width=Math.round(innerWidth*dpr);layer.canvas.height=Math.round(innerHeight*dpr);layer.canvas.style.width=innerWidth+'px';layer.canvas.style.height=innerHeight+'px';layer.ctx.setTransform(dpr,0,0,dpr,0,0)}}
  addEventListener('resize',resize,{passive:true});resize();
  function maxParticles(frontLayer){let density=getNum('ember-density');if(X.weakDevice)density*=.68;if(X.reduced)density*=.35;return Math.round(density*(frontLayer?.24:1))}
  function allowedTypes(frontLayer){const types=[];if(getBool('embers'))types.push('ember');if(getBool('ash'))types.push('ash');if(getBool('hot-dust')&&!frontLayer)types.push('dust');if(getBool('sparks')&&Math.random()<.22)types.push('spark');return types.length?types:['ash']}
  function spawn(layer){const types=allowedTypes(layer.front),type=types[Math.floor(Math.random()*types.length)],p={type,x:Math.random()*innerWidth,y:innerHeight+20+Math.random()*80,life:0,rot:Math.random()*6.28};
    const motion=getNum('motion-intensity')/100;
    if(type==='ember')Object.assign(p,{vx:(Math.random()-.5)*.25,vy:-(.22+Math.random()*.48)*(0.5+motion),size:(layer.front?2.6:1)+(Math.random()*(layer.front?3.8:2.8)),max:7500+Math.random()*9000,alpha:.25+Math.random()*.55,flicker:Math.random()*8});
    if(type==='spark')Object.assign(p,{vx:(Math.random()-.5)*1.8,vy:-(2.4+Math.random()*3.5),size:layer.front?2.2:1.3,max:380+Math.random()*600,alpha:.7+Math.random()*.3,len:7+Math.random()*18});
    if(type==='ash')Object.assign(p,{vx:(Math.random()-.5)*.35,vy:-(.12+Math.random()*.24),size:(layer.front?3:1.5)+Math.random()*(layer.front?6:4),max:9000+Math.random()*13000,alpha:.08+Math.random()*.24,turn:(Math.random()-.5)*.018,fallAt:.4+Math.random()*.4,spriteIndex:Math.floor(Math.random()*3)});
    if(type==='dust')Object.assign(p,{vx:.12+Math.random()*.4,vy:(Math.random()-.5)*.04,size:18+Math.random()*55,max:12000+Math.random()*13000,alpha:.015+Math.random()*.04});
    layer.particles.push(p);
  }
  function drawParticle(ctx,p,dt){p.life+=dt;const t=p.life/p.max;if(p.type==='ash'&&t>p.fallAt)p.vy+=.00012*dt;p.x+=(p.vx+wind*(p.type==='dust'?1.8:.6))*dt/16;p.y+=p.vy*dt/16;p.rot+=(p.turn||.002)*dt;p.alphaNow=(p.alpha||.3)*Math.sin(Math.PI*Math.min(1,t));
    ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rot||0);ctx.globalAlpha=Math.max(0,p.alphaNow);
    if(p.type==='ember'){const flick=.75+.25*Math.sin(p.life*.012+p.flicker),sprite=readySprite('ember');if(sprite){const size=p.size*flick*7;ctx.drawImage(sprite,-size/2,-size/2,size,size)}else{ctx.fillStyle=`rgba(255,${125+Math.round(flick*70)},55,1)`;ctx.shadowBlur=6+p.size;ctx.shadowColor='rgba(255,116,35,.65)';ctx.beginPath();ctx.arc(0,0,p.size*flick,0,Math.PI*2);ctx.fill()}}
    else if(p.type==='spark'){const sprite=readySprite('spark');if(sprite){const width=Math.max(10,p.len*2.2),height=Math.max(4,p.size*5);ctx.rotate(-.65);ctx.drawImage(sprite,-width*.85,-height/2,width,height)}else{ctx.strokeStyle='rgba(255,196,103,.95)';ctx.lineWidth=p.size;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(-p.vx*p.len,p.len);ctx.stroke()}}
    else if(p.type==='ash'){const sprite=readySprite('ash',p.spriteIndex||0);if(sprite){const size=p.size*3.2;ctx.drawImage(sprite,-size/2,-size/2,size,size)}else{ctx.fillStyle='rgba(38,34,31,.9)';ctx.fillRect(-p.size/2,-p.size/5,p.size,p.size*.42)}}
    else{const g=ctx.createRadialGradient(0,0,0,0,0,p.size);g.addColorStop(0,'rgba(178,112,63,.45)');g.addColorStop(1,'rgba(178,112,63,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,p.size,0,Math.PI*2);ctx.fill()}
    ctx.restore();return t>=1||p.y<-120||p.x<-160||p.x>innerWidth+160}
  function active(){return !document.hidden&&!document.body.classList.contains('performance-mode')&&!document.body.classList.contains('no-particles')}
  function frame(now){const dt=Math.min(40,now-last);last=now;if(active()&&running){if(getBool('turbulence')&&now>nextGust){targetWind=(Math.random()-.5)*1.5;nextGust=now+3000+Math.random()*7000}else if(now>nextGust-1600)targetWind*=.94;wind+=(targetWind-wind)*.015;for(const layer of contexts){const ctx=layer.ctx;ctx.clearRect(0,0,innerWidth,innerHeight);const max=maxParticles(layer.front);if(layer.front&&!getBool('front-particles'))layer.particles.length=0;else while(layer.particles.length<max)spawn(layer);layer.particles=layer.particles.filter(p=>!drawParticle(ctx,p,dt));}}else{for(const layer of contexts)layer.ctx.clearRect(0,0,innerWidth,innerHeight)}raf=requestAnimationFrame(frame)}
  raf=requestAnimationFrame(frame);
  document.addEventListener('visibilitychange',()=>{last=performance.now()});

  function applyVisualSettings(){document.documentElement.style.setProperty('--gs-effect-opacity',getNum('effect-opacity')/100);document.documentElement.style.setProperty('--gs-map-texture-opacity',getBool('map-texture')?.18:.04);document.documentElement.style.setProperty('--gs-menu-emblem-opacity',getBool('clan-texture')?.085:0);clouds.style.display=getBool('hot-dust')&&!document.body.classList.contains('performance-mode')?'block':'none';for(const layer of contexts)layer.particles.length=0;syncContemplative()}
  const settingsHost=document.getElementById('settingsContent');
  function injectSettings(){if(!settingsHost||settingsHost.querySelector('[data-guerras-experience-settings]'))return;settingsHost.insertAdjacentHTML('beforeend',`<section class="experience-settings-section" data-guerras-experience-settings><h3>Atmosfera de Guerras de Sangue</h3><p class="experience-settings-note">Controles específicos deste livro. Alterá-los não modifica Ruínas dos Céus.</p>${X.makeToggle({key:'embers',prefix:P,label:'Brasas',description:'Pontos luminosos lentos e irregulares.',value:getBool('embers')})}${X.makeToggle({key:'sparks',prefix:P,label:'Faíscas',description:'Riscos rápidos, raros e localizados.',value:getBool('sparks')})}${X.makeToggle({key:'ash',prefix:P,label:'Cinzas',description:'Fragmentos escuros com subida e queda.',value:getBool('ash')})}${X.makeToggle({key:'hot-dust',prefix:P,label:'Poeira quente',description:'Manchas horizontais quase transparentes.',value:getBool('hot-dust')})}${X.makeToggle({key:'turbulence',prefix:P,label:'Turbulência',description:'Rajadas imprevisíveis mudam a direção.',value:getBool('turbulence')})}${X.makeToggle({key:'front-particles',prefix:P,label:'Partículas dianteiras',description:'Elementos raros próximos da câmara.',value:getBool('front-particles')})}${X.makeToggle({key:'clan-texture',prefix:P,label:'Marcas de clã no menu',description:'Selos históricos e identidade contextual.',value:getBool('clan-texture')})}${X.makeToggle({key:'map-texture',prefix:P,label:'Textura cartográfica',description:'Rios, fronteiras e linhas apagadas.',value:getBool('map-texture')})}${X.makeToggle({key:'metal-reflection',prefix:P,label:'Reflexos de metal',description:'Reflexos breves em controles importantes.',value:getBool('metal-reflection')})}${X.makeRange({key:'ember-density',prefix:P,label:'Densidade atmosférica',description:'Quantidade máxima, adaptada ao dispositivo.',value:getNum('ember-density'),min:10,max:100})}${X.makeRange({key:'motion-intensity',prefix:P,label:'Intensidade do movimento',description:'Velocidade geral das partículas.',value:getNum('motion-intensity'),min:0,max:100})}${X.makeRange({key:'effect-opacity',prefix:P,label:'Opacidade dos efeitos',description:'Visibilidade geral da atmosfera.',value:getNum('effect-opacity'),min:20,max:100})}</section>`)}
  if(settingsHost){X.attachSettings(settingsHost,()=>{X.storage.set(P+'customized','1');applyVisualSettings();setTimeout(injectSettings)});new MutationObserver(injectSettings).observe(settingsHost,{childList:true})}
  const profileValues={
    full:{embers:1,sparks:1,ash:1,'hot-dust':1,turbulence:1,'front-particles':1,'clan-texture':1,'map-texture':1,'metal-reflection':1,'ember-density':100,'motion-intensity':62,'effect-opacity':96},
    normal:{embers:1,sparks:1,ash:1,'hot-dust':1,turbulence:1,'front-particles':1,'clan-texture':1,'map-texture':1,'metal-reflection':1,'ember-density':92,'motion-intensity':52,'effect-opacity':86},
    performance:{embers:0,sparks:0,ash:0,'hot-dust':0,turbulence:0,'front-particles':0,'clan-texture':1,'map-texture':0,'metal-reflection':0,'ember-density':10,'motion-intensity':0,'effect-opacity':32}
  };
  function applyProfile(name){const values=profileValues[name];if(!values)return;Object.entries(values).forEach(([k,v])=>X.storage.set(P+k,v));X.storage.set(P+'customized','0');setTimeout(applyVisualSettings,60)}
  document.addEventListener('click',e=>{const p=e.target.closest('[data-preset]')?.dataset.preset;if(p)applyProfile(p);if(e.target.closest('#performanceToggle'))setTimeout(()=>X.toast(document.body.classList.contains('performance-mode')?'Modo desempenho ativado':'Modo equilibrado ativado'),70)});
  X.observePerformance(()=>applyVisualSettings());

  function updateClanContext(){const sidebar=document.getElementById('sidebar');if(!sidebar)return;const route=location.hash.replace(/^#\/?/,'');const match=route.match(/^clan\/([^/]+)/);let name='';if(match){const clan=(window.DI_DATA?.clans||[]).find(c=>c.slug===match[1]||c.id===match[1]);name=clan?.name||match[1].replaceAll('-',' ')}sidebar.dataset.clanContext=name;document.body.dataset.clansContext=String(route==='clans'||!!match)}
  addEventListener('hashchange',updateClanContext);updateClanContext();

  let contemplateShell=null,contemplateCanvas=null,contemplateCtx=null,contemplateParticles=[];
  function createContemplative(){if(contemplateShell)return contemplateShell;contemplateShell=document.createElement('section');contemplateShell.className='contemplative-shell guerras-contemplative';contemplateShell.id='guerrasContemplative';contemplateShell.setAttribute('aria-hidden','true');contemplateShell.innerHTML='<div class="contemplative-scene"><div class="guerras-contemplative-art"></div><canvas id="warContemplativeCanvas" aria-hidden="true"></canvas><div class="guerras-contemplative-fog"></div><button class="contemplative-back" type="button" data-close-contemplative title="Voltar à página">← Voltar</button><button class="contemplative-music-action" type="button" data-contemplative-music title="Ligar ou desligar música">♪ Música</button><div class="contemplative-caption">Kaendar · território vigiado junto ao Rio Grande</div></div>';document.body.append(contemplateShell);contemplateCanvas=contemplateShell.querySelector('canvas');contemplateCtx=contemplateCanvas.getContext('2d');resizeContemplative();return contemplateShell}
  function resizeContemplative(){if(!contemplateCanvas)return;const dpr=Math.min(devicePixelRatio||1,1.5);contemplateCanvas.width=innerWidth*dpr;contemplateCanvas.height=innerHeight*dpr;contemplateCtx.setTransform(dpr,0,0,dpr,0,0)}
  addEventListener('resize',resizeContemplative,{passive:true});
  function drawContemplative(){if(!contemplateShell?.classList.contains('open')){requestAnimationFrame(drawContemplative);return}contemplateCtx.clearRect(0,0,innerWidth,innerHeight);while(contemplateParticles.length<Math.max(8,Math.round(maxParticles(false)*.34))){const types=['ember','ash','dust'];const type=types[Math.floor(Math.random()*types.length)],p={type,x:Math.random()*innerWidth,y:innerHeight+20,life:0,rot:0};if(type==='ember')Object.assign(p,{vx:(Math.random()-.5)*.2,vy:-.2-Math.random()*.35,size:1+Math.random()*2.5,max:9000+Math.random()*9000,alpha:.18+Math.random()*.3,flicker:1});if(type==='ash')Object.assign(p,{vx:(Math.random()-.5)*.25,vy:-.08-Math.random()*.18,size:2+Math.random()*4,max:12000+Math.random()*9000,alpha:.08+Math.random()*.14,turn:.004,fallAt:.6});if(type==='dust')Object.assign(p,{vx:.12+Math.random()*.3,vy:0,size:20+Math.random()*45,max:16000,alpha:.02});contemplateParticles.push(p)}contemplateParticles=contemplateParticles.filter(p=>!drawParticle(contemplateCtx,p,16));requestAnimationFrame(drawContemplative)}
  requestAnimationFrame(drawContemplative);
  function syncContemplative(){if(contemplateShell&&document.body.classList.contains('performance-mode'))contemplateParticles.length=0}
  function openContemplative(){const shell=createContemplative();shell.classList.add('open');shell.setAttribute('aria-hidden','false');document.body.classList.add('contemplative-active');shell.querySelector('.contemplative-back')?.focus()}
  function closeContemplative(){if(!contemplateShell)return;contemplateShell.classList.remove('open');contemplateShell.setAttribute('aria-hidden','true');document.body.classList.remove('contemplative-active');contemplateParticles.length=0;document.querySelector('[data-contemplative="guerras"]')?.focus()}
  document.addEventListener('click',e=>{if(e.target.closest('[data-contemplative="guerras"]'))openContemplative();if(e.target.closest('[data-close-contemplative]'))closeContemplative();if(e.target.closest('[data-contemplative-music]'))document.querySelector('[data-music-power]')?.click()});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('contemplative-active')){e.preventDefault();closeContemplative()}});

  injectSettings();applyVisualSettings();
})();
