(()=>{const R=window.RS,{D,st,H,E,media}=R;
const map={fauna:'fauna',flora:'flora',alimentos:'foods',conceitos:'concepts'};
const titles={fauna:['Fauna','Animais do céu e da superfície, suas características e citações.'],flora:['Flora','Plantas de Etérea e Nadirion, seus usos e aparições.'],alimentos:['Alimentos','Comidas do céu e recursos que sustentam a sobrevivência.'],conceitos:['Conceitos e leis','Ideias, ritos e instituições que organizam a vida eterí e mudam de significado após a Queda.']};
const fallback={fauna:'',flora:'',alimentos:'',conceitos:''};
function itemsFor(k){return D.common?.entities?.[map[k]]||[]}
function ordered(k){const a=[...itemsFor(k)];return a.sort(st.sort==='count'?(x,y)=>(y.citations||0)-(x.citations||0)||x.name.localeCompare(y.name,'pt-BR'):(x,y)=>x.name.localeCompare(y.name,'pt-BR'))}
function routeFor(k,item){return k==='conceitos'?`conceito/${item.slug}`:`${k}/${item.slug}`}
function listSection(title,items){return items?.length?`<section class="concept-rich-block"><h2>${E(title)}</h2><ul>${items.map(x=>`<li>${R.linkify(x)}</li>`).join('')}</ul></section>`:''}
function relatedButton(route,title,subtitle=''){return `<button class="mini-related-button" data-go="${E(route)}"><strong>${E(title)}</strong>${subtitle?`<small>${E(subtitle)}</small>`:''}</button>`}
R.pages.lore=k=>{const [title,sub]=titles[k]||['Lore','Itens do mundo.'],items=ordered(k),isConcept=k==='conceitos';const cards=items.map(item=>{const target=routeFor(k,item);return `<article class="card lore-stage11-card click ${isConcept?'concept-stage12-card':''}" data-go="${E(target)}" tabindex="0" role="link">${media(item.image||fallback[k],item.name,isConcept?'◫':'✦','lorepic symbol')}<div class="lore-stage11-card-copy"><p class="meta">${isConcept?E(item.type||'Conceito'):`${item.citations||0} ${(item.citations||0)===1?'citação':'citações'}`}</p><h3>${E(item.name)}</h3><p>${E(item.summary||'Descrição em preparação.')}</p>${isConcept?`<span class="concept-open-label">Abrir conceito →</span>`:''}</div></article>`}).join('');const tools=isConcept?'':`<div class="filters lore-order-tools"><button class="${st.sort==='alpha'?'active':''}" data-sort="alpha">A–Z</button><button class="${st.sort==='count'?'active':''}" data-sort="count">Mais citados</button><button data-export="${E(k)}">Exportar não citados</button></div>`;return H('Lore',title,sub)+tools+`<div class="grid lore-stage11-grid">${cards||'<div class="empty">Nenhum item.</div>'}</div>`};
R.pages.loreItem=(k,id)=>{const item=itemsFor(k).find(x=>x.slug===id||x.id===id);if(!item)return R.err();const [title]=titles[k]||['Lore'];const mentions=item.citationDetails||[];const isConcept=k==='conceitos';
if(isConcept){
  const chars=(item.relatedCharacters||[]).map(cid=>D.common?.findById?.('characters',cid)).filter(Boolean);
  const places=(item.relatedPlaces||[]).map(pid=>D.common?.findById?.('places',pid)).filter(Boolean);
  const chapters=(item.chapterNumbers||[]).map(n=>D.common?.entities?.chapters?.find(ch=>Number(ch.number)===Number(n))).filter(Boolean);
  return `<button class="back" data-go="conceitos">← Voltar</button><section class="detailhero lore-stage11-hero concept-stage12-hero">${media(item.image||fallback.conceitos,item.name,'◫','portrait avatar big')}<article class="panel"><p class="eyebrow">${E(item.type||title)}</p><h1>${E(item.name)}</h1><p class="lead">${E(item.summary||'')}</p></article></section><section class="concept-stage12-layout"><article class="panel concept-stage12-main"><section class="concept-rich-block"><h2>Definição</h2><p>${R.linkify(item.definition||item.summary||'')}</p></section><section class="concept-rich-block"><h2>Origem</h2><p>${R.linkify(item.origin||'Não estabelecida.')}</p></section><section class="concept-rich-block"><h2>Funcionamento conhecido</h2><p>${R.linkify(item.knownFunctioning||'Não estabelecido.')}</p></section>${listSection('Interpretações',item.interpretations)}${listSection('Ambiguidades',item.ambiguities)}${listSection('Evolução no livro',item.evolution)}</article><aside class="panel concept-stage12-context"><h2>Personagens relacionadas</h2><div class="mini-related-list">${chars.length?chars.map(c=>relatedButton(`personagem/${c.slug}`,c.name,c.alias||c.importance||'')).join(''):'<p class="empty-inline">Nenhuma personagem ligada.</p>'}</div><h2>Capítulos relacionados</h2><div class="mini-related-list">${chapters.length?chapters.map(ch=>relatedButton(`capitulo/${ch.number}`,`Capítulo ${ch.number}`,ch.title)).join(''):'<p class="empty-inline">Nenhum capítulo ligado.</p>'}</div><h2>Lugares relacionados</h2><div class="mini-related-list">${places.length?places.map(p=>relatedButton(`lugar/${p.slug}`,p.name,p.type||'Lugar')).join(''):'<p class="empty-inline">Nenhum lugar ligado.</p>'}</div></aside></section>`;
}
const fields=[['Características',item.characteristics],['Habitat',item.habitat],['Usos',Array.isArray(item.uses)?item.uses.join('\n'):item.uses]].filter(x=>x[1]);return `<button class="back" data-go="${k}">← Voltar</button><section class="detailhero lore-stage11-hero">${media(item.image||fallback[k],item.name,'✦','portrait avatar big')}<article class="panel"><p class="eyebrow">${E(title)}</p><h1>${E(item.name)}</h1><p class="lead">${E(item.summary||'')}</p><div class="stats"><span class="stat">${item.citations||0} ${(item.citations||0)===1?'citação':'citações'}</span></div></article></section><section class="panel lore-stage11-description"><h2>Descrição completa</h2>${String(item.fullDescription||item.summary||'').split(/\n\s*\n/).filter(Boolean).map(p=>`<p>${E(p)}</p>`).join('')}</section>${fields.length?`<section class="grid lore-stage11-fields">${fields.map(([label,value])=>`<article class="card"><h3>${E(label)}</h3>${String(value).split('\n').filter(Boolean).map(p=>`<p>${E(p)}</p>`).join('')}</article>`).join('')}</section>`:''}<section class="panel lore-citations-section"><div class="section-heading"><div><p class="eyebrow">Citações no livro</p><h2>${item.citations||0} ${(item.citations||0)===1?'vez citado':'vezes citado'}</h2><p>Todas as menções localizadas no manuscrito canônico usado nesta etapa.</p></div></div>${mentions.length?`<div class="lore-citation-list">${mentions.map(m=>`<article class="lore-citation"><button class="lore-citation-chapter" data-go="capitulo/${m.chapter}">Capítulo ${m.chapter} — ${E(m.chapterTitle||'')}</button><blockquote>“${E(m.quote)}”</blockquote><p>${E(m.context||'')}</p></article>`).join('')}</div>`:'<p class="empty-inline">Este item ainda não foi citado diretamente no manuscrito.</p>'}</section>`};
R.pages.conceito=id=>R.pages.loreItem('conceitos',id);
})();
