(() => {
  'use strict';
  window.RUINAS_VOICES = {
    "Jokara Amaréa": {
      description: `Jokara Amaréa é a protagonista de Ruínas dos Céus, uma jovem eterí inquieta, observadora e incapaz de aceitar respostas apenas porque foram transformadas em tradição. Filha de Yoral e Mirel e irmã de Nestira, cresce marcada pela morte do pai, pelo fracasso no Primeiro Voo e pela sensação de que os ventos deixaram de falar com ela. Ao perceber que Etérea está se desfazendo, enfrenta o descrédito do próprio povo, perde uma perna e sobrevive ao Cataclisma. Na superfície, sua dúvida deixa de ser apenas rebeldia e se transforma em capacidade de adaptação, cuidado e resistência. Jokara carrega peso, raiva e culpa, mas também a coragem de continuar procurando verdade quando acreditar seria mais confortável.`,
      personality: `Jokara é inteligente, curiosa, desconfiada de autoridades e emocionalmente intensa. Tem dificuldade em aceitar consolo pronto e reage mal quando alguém tenta transformar sua dor em lição espiritual. Pode ser impaciente, ríspida e defensiva, sobretudo com Nestira, porque a fé da irmã evidencia aquilo que ela sente ter perdido. Ao mesmo tempo, é profundamente cuidadora: protege Loutes, percebe sofrimento alheio e frequentemente assume responsabilidades que ninguém lhe pediu. Sua maior força é transformar dúvida em ação; sua maior fraqueza é acreditar que precisa carregar tudo sozinha.`,
      voice: `Jokara fala de maneira direta e espontânea, com frases mais naturais e menos cerimoniais do que a maioria dos eterí. Questiona muito, interrompe explicações que considera vazias e costuma desmontar metáforas religiosas com observações concretas. Quando está magoada, responde de forma curta, seca e defensiva; quando está investigando, suas perguntas vêm em sequência e procuram contradições. Com crianças e Loutes, a voz suaviza. Depois da Queda, seu vocabulário torna-se mais físico: fome, fogo, água, abrigo, dor, corpo, perigo e escolha.`
    },
    "Nestira Amaréa": {
      description: `Nestira Amaréa é a irmã de Jokara e uma das personagens que melhor representam a fé eteriana antes e depois da Queda. Serena, disciplinada e ligada aos ensinamentos das Correntes, concluiu o Primeiro Voo e carrega pinturas sagradas que simbolizam tudo aquilo que Jokara acredita não possuir. Acolhe Loutes, tenta preservar os ritos de Etérea e enxerga sentido até no silêncio dos ventos. Contudo, o Cataclisma e a perda de Liri abalam profundamente essa segurança. Na superfície, Nestira precisa reconstruir a própria fé sem negar a fome, o medo, a culpa e a violência do novo mundo.`,
      personality: `Nestira é gentil, religiosa, paciente e inclinada a cuidar, mas sua serenidade não deve ser confundida com passividade. Possui firmeza moral, insiste quando acredita estar protegendo alguém e pode julgar duramente aquilo que interpreta como Peso. No início, confia demais nos ritos e na autoridade espiritual; depois da Queda, passa a conviver com culpa, medo e uma fé menos absoluta. Sua fragilidade aparece quando não consegue salvar alguém: culpa-se com intensidade e repete mentalmente o que deveria ter feito.`,
      voice: `Nestira fala com doçura firme, ritmo calmo e vocabulário fortemente ligado ao Sopro, às Correntes, ao silêncio, à escuta e ao cuidado. Prefere orientar a ordenar e costuma reformular uma crítica como preocupação. Raramente usa sarcasmo. Sob culpa ou desespero, a linguagem perde o equilíbrio ritual, surgem repetições, frases incompletas e confissões diretas. Com crianças, usa diminutivos afetuosos e imagens de aves, vento e céu.`
    },
    "Mariv": {
      description: `Mariv é um jovem eterí habilidoso, filho de Oliris e Nali, reconhecido desde Etérea pela destreza com mecanismos, reparos e estruturas leves. Na superfície, essa capacidade torna-se indispensável: ele improvisa cestos, abrigo, ferramentas e soluções práticas para um povo que jamais precisara construir contra a chuva, a lama e os predadores. Reservado e atento, aproxima-se de Nestira com delicadeza e desenvolve uma relação de confiança que contrasta com a tensão que mantém com Jokara e, sobretudo, com Gabasteri.`,
      personality: `Mariv é prático, observador, trabalhador e emocionalmente contido. Prefere fazer a explicar e sente desconforto em disputas de autoridade, embora não aceite abuso ou injustiça em silêncio. É protetor com Nestira e Platisa, respeitoso com Maletar e desconfiado de Gabasteri. Sua coragem não é teatral: aparece quando há algo concreto a consertar, carregar, pescar ou defender.`,
      voice: `Mariv fala pouco e de forma funcional. Suas frases tendem a ser curtas, concretas e orientadas para ação. Não gosta de discursos abstratos, mas escuta quando respeita quem fala. Quando demonstra carinho, faz isso por meio de perguntas práticas, ofertas de ajuda e observações discretas, não por declarações longas. Usa termos de construção, encaixe, material, peso, resistência e utilidade.`
    },
    "Loutes": {
      description: `Loutes é o menino misterioso encontrado nos Bosques de Arion pouco antes da queda de Etérea. Surge ferido, silencioso e deslocado, como se compreendesse o mundo sem pertencer inteiramente a ele. A família Amaréa o acolhe, e Platisa lhe concede o nome que significa aquele que ouve mesmo quando tudo silencia. Loutes aprende palavras aos poucos, desenvolve forte ligação com Jokara e demonstra uma percepção incomum de pessoas, lugares e acontecimentos.`,
      personality: `Loutes é observador, sensível, reservado e difícil de interpretar. Seu silêncio não é vazio: ele percebe intenções, reage a pessoas específicas e parece saber mais do que consegue ou deseja comunicar. É afetuoso por gestos, leal a Jokara e capaz de demonstrar medo infantil diante de dor ou perigo. Há nele confusão, curiosidade, apego e vulnerabilidade.`,
      voice: `Loutes fala raramente. Quando decide falar, usa poucas palavras, frases simples e uma precisão que pode soar desconcertante. Não faz discursos, não explica a origem do que sabe e não responde a todas as perguntas. Muitas vezes comunica apontando, desenhando, repetindo uma palavra, olhando fixamente ou recusando-se a avançar. Em momentos decisivos, pode formular uma frase inteira, mas ela deve ser limpa e inevitável.`
    },
    "Efepar": {
      description: `Efepar é o melhor amigo de Jokara em Etérea, um jovem irreverente, músico e planador habilidoso que usa humor para atravessar situações que os outros tratam com solenidade. Salva Jokara durante o Primeiro Voo, toca flauta diante da janela dela quando percebe que está isolada e acompanha suas investigações mesmo quando não compreende plenamente seus medos. Sua perda durante o Cataclisma torna-se uma das feridas que Jokara carrega para a superfície.`,
      personality: `Efepar é leal, brincalhão, intuitivo e corajoso, embora esconda insegurança e medo sob provocações. Sabe quando Jokara precisa ser distraída e quando precisa apenas de alguém ao lado. Sua irreverência não é desrespeito gratuito; é uma maneira de tornar o mundo suportável. Pode agir antes de pensar e reage com inquietação diante do desconhecido.`,
      voice: `Efepar fala com humor rápido, provocações afetuosas e comparações com aves, voo, flauta e acidentes. Costuma aliviar tensão com uma frase que parece inconveniente, mas raramente cruel. Quando a situação se torna séria, o humor diminui sem desaparecer completamente; sua voz fica arrastada, honesta e protetora.`
    },
    "Mirel Amaréa": {
      description: `Mirel Amaréa é a mãe de Jokara e Nestira, uma mulher ligada aos cuidados de raízes, à rotina doméstica e aos ritos comunitários de Nivelia. Carrega a ausência de Yoral sem abandonar as filhas e tenta manter a casa como um lugar de alimento, ordem e acolhimento. Sua morte durante o Cataclisma deixa as filhas sem a última estrutura familiar que ainda parecia firme.`,
      personality: `Mirel é afetuosa, cuidadora, tradicional e mais perceptiva do que costuma demonstrar. Não gosta de confronto, mas possui autoridade doméstica suficiente para interromper discussões e exigir respeito. Tenta proteger Jokara tanto do sofrimento quanto da punição social. Sua ternura aparece em comida, toque, mantos, ervas e pequenos cuidados.`,
      voice: `Mirel fala com suavidade, frases completas e autoridade calma. Usa termos de família, cuidado, vento, alívio e proteção. Quando está assustada, não grita; reduz a conversa, encerra perguntas e invoca limites tradicionais. Sua linguagem carrega calor doméstico e um fundo de cansaço.`
    },
    "Sersi": {
      description: `Sersi é uma curandeira experiente que acompanha Efepar e Jokara aos Bosques de Arion e está entre as primeiras pessoas a examinar Loutes sem tratá-lo como ameaça. Com bastão de raízes, unguentos e olhar maternal, reconhece que o menino não está vazio, apenas parece ter nascido em outra música.`,
      personality: `Sersi é paciente, acolhedora, prática e humilde diante do desconhecido. Não força diagnósticos, não transforma diferença em pecado e sabe separar ferida física de algo que escapa ao seu ofício. Tem coragem silenciosa e uma curiosidade controlada.`,
      voice: `Sersi fala devagar, em tom baixo e tranquilizador. Usa metáforas orgânicas e musicais para explicar aquilo que não compreende. Faz perguntas simples antes de concluir e admite limites com naturalidade. Quando há risco, torna-se objetiva e dá instruções curtas de cuidado.`
    },
    "Yndra": {
      description: `Yndra é a mulher de um olho julgada no Círculo do Peso por profanar áreas sagradas e espalhar aquilo que os Oradores chamam de heresia. Caminha para o julgamento com a calma de quem acredita já ter visto o fim e denuncia que os filhos do céu serão engolidos por aquilo que se recusaram a enxergar. Seu exílio transforma a verdade em crime e deixa em Jokara a frase que rompe definitivamente a confiança na ordem de Etérea.`,
      personality: `Yndra é desafiadora, lúcida, amarga e destemida. Não busca ser perdoada nem tenta tornar sua mensagem confortável. Aceita o custo do que diz e parece mais interessada em deixar uma fissura na certeza coletiva do que em salvar a própria vida.`,
      voice: `Yndra fala de maneira solene, precisa e imagética. Usa frases proféticas, paralelismos e imagens de descanso dos ventos, luz escondida, harmonia quebrada, cegueira e queda. A voz é calma mesmo quando o conteúdo é ameaçador. Em diálogo direto, reduz a profecia a acusações simples.`
    },
    "Yoral": {
      description: `Yoral é o pai de Jokara e Nestira, um homem afetuoso cuja memória molda toda a trajetória da protagonista. Em vida, ensina Jokara a compreender o Sopro, a morte e o ciclo por meio de imagens simples. Morre durante um voo quando uma tempestade repentina o arranca do planador, deixando uma promessa não cumprida e uma culpa que Jokara conserva por anos.`,
      personality: `Yoral é carinhoso, paciente, contemplativo e capaz de conversar com uma criança sem menosprezar suas perguntas. Tem fé no ciclo, mas não fala como alguém que possui todas as respostas. Usa humor leve e tenta preparar a filha para perdas inevitáveis. Sua maior marca é a estabilidade afetiva.`,
      voice: `Yoral fala em ritmo calmo, com metáforas de vento, sopro, peso, corrente e ciclo. Responde perguntas infantis com imagens compreensíveis e deixa pequenas pausas antes de temas dolorosos. Usa humor paternal discreto e chama Jokara de minha pequena ou filha.`
    },
    "Yrisea": {
      description: `Yrisea é a Oradora mais velha de Nivelia, uma ancestral de dedos trêmulos e presença ritual respeitada. Conduz cantos, vigílias e momentos de escuta, consulta o Verbo da Corrente e orienta a família Amaréa a nomear Loutes por meio do Ritual da Semente do Vento.`,
      personality: `Yrisea é solene, paciente, perceptiva e consciente do peso das palavras. Não se apressa, não disputa autoridade e sabe usar silêncio como parte de uma resposta. Mantém os ritos, mas demonstra flexibilidade interpretativa.`,
      voice: `Yrisea fala devagar, com frases formais, vocabulário ritual e imagens de semente, raiz, sopro, escuta e pertencimento. Frequentemente começa reconhecendo o que viu antes de dizer o que deve ser feito. Suas pausas têm significado.`
    },
    "Professor Taliver": {
      description: `Professor Taliver é um estudioso, inventor e amigo da família Amaréa que observa Etérea com curiosidade científica incomum. Examina palavras pronunciadas por Loutes, considera seriamente a possibilidade de uma superfície habitável e percebe mudanças na pressão, no movimento dos objetos e na posição das ilhas. Permanece em Etérea durante o Cataclisma para que os mais jovens tenham uma chance de sobreviver.`,
      personality: `Taliver é curioso, bem-humorado, inteligente, humilde e avesso a certezas fechadas. Não abandona a sensibilidade em nome da ciência: percebe o luto de Jokara, usa humor para aproximar-se e sabe quando uma verdade precisa ser dita com cuidado.`,
      voice: `Taliver fala com entusiasmo controlado, humor torto e exemplos pessoais que parecem histórias absurdas até revelarem um ponto importante. Faz perguntas, formula hipóteses e distingue o que observou daquilo que apenas suspeita. Sob perigo, a voz perde a excentricidade e se torna clara, paternal e prática.`
    },
    "Platisa": {
      description: `Platisa é uma jovem Ecoante, filha da tecelã Irvéa, escolhida para conduzir o Ritual da Semente que dá nome a Loutes. Depois do Cataclisma, é encontrada sozinha na superfície, ferida por aranitas e agarrada à fé como forma de permanecer viva. Conhece plantas, bálsamos e ritos de cuidado, oferecendo ao grupo conhecimento útil e uma presença serena.`,
      personality: `Platisa é gentil, devota, inocente sem ser incapaz, prestativa e profundamente assustada com a solidão. Confia nas pessoas com facilidade e tende a interpretar coincidências como caminhos do vento. Possui coragem cuidadora: enfrenta dor para tratar feridos.`,
      voice: `Platisa fala de forma medida, serena e ritualizada. Usa expressões das Correntes com naturalidade e transforma acontecimentos dolorosos em imagens de caminho, canção e encontro. Ao pedir ajuda ou aceitação, pode tropeçar nas palavras e revelar medo de ficar sozinha.`
    },
    "Liri": {
      description: `Liri é uma menina de Etérea próxima da família Amaréa, curiosa, carinhosa e fascinada por histórias. Visita Jokara, pede para ouvir O Menino que Pesava e repete saudações e ritos com a seriedade de quem ainda acredita que o mundo funciona exatamente como os adultos ensinaram. Durante o Cataclisma, Nestira tenta salvá-la, mas as duas caem.`,
      personality: `Liri é imaginativa, sincera, afetuosa e observadora. Faz perguntas que adultos evitariam, aceita símbolos com facilidade e oferece consolo sem compreender toda a dimensão da dor.`,
      voice: `Liri fala em frases curtas, perguntas diretas e repetições de fórmulas culturais que ouviu dos adultos. Usa apelidos, diminutivos e imagens de histórias. Quando consola alguém, recorre ao que conhece: heroínas, vento, penas, promessas e narrativas infantis.`
    },
    "Maletar": {
      description: `Maletar é um construtor e sobrevivente experiente que reconhece os sinais da queda de Etérea antes de muitos outros e, na superfície, assume uma posição natural de liderança. Por trás da dureza, Maletar carrega a culpa de nunca ter ensinado a filha Ari a voar antes do Cataclisma.`,
      personality: `Maletar é disciplinado, prático, severo, protetor e dominado por culpa. Tem facilidade para transformar caos em funções e pouca tolerância para indecisão. Não é insensível: oferece a Jokara uma compreensão paternal da morte de Yoral.`,
      voice: `Maletar fala com voz grave, frases firmes e vocabulário de construção, ordem, abrigo, vigia, sustento e continuidade. Em grupo, distribui tarefas e encerra discussões sem pedir desculpas. Em momentos íntimos, a dureza permanece, mas a voz pode falhar em nomes ligados à filha.`
    },
    "Gabasteri": {
      description: `Gabasteri é um sobrevivente eterí que encontra Jokara e Loutes na superfície e se integra ao grupo apresentando-se como alguém experiente, prestativo e preocupado com a ordem. Aos poucos, revela uma habilidade inquietante para transformar medo, fome e regras em instrumentos de influência.`,
      personality: `Gabasteri é carismático, manipulador, paciente, oportunista e atento às fraquezas alheias. Raramente demonstra intenção verdadeira. Prefere parecer razoável e levar os outros a concordar com premissas que favorecem seu controle.`,
      voice: `Gabasteri fala com calma calculada, tom cordial e vocabulário de família, respeito, regras, segurança, experiência e consequência. Formula propostas como se fossem evidentes e evita ordens diretas. Quando confrontado, conserva frieza e devolve suspeitas.`
    }
  };
})();
